### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [parwat08/random-emoji-robbyrussell#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by parwatcodes** [comment]
Added theme screenshot

@unixorn 
This theme is built with random-emoji and robbyrussell with the fish shell's fish icon. As per mine custom needs.

**Comment by unixorn** [comment]
Added to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), thanks!
