### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [parwat08/random-emoji-robbyrussell#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by parwatcodes** [comment]
@unixorn How did I miss this issue? Sorry for this late.

Added MIT license. https://github.com/parwatcodes/random-emoji-robbyrussell/pull/3

**Comment by unixorn** [comment]
No problem, it happens to everyone.
